'use client';

import React, { useState } from 'react';
import { Lightbulb, Shield, Target, AlertTriangle, Flame } from 'lucide-react';
import { CoachingTip } from '@/lib/insights';

interface Props {
    COACHING: CoachingTip[];
}

export default function CoachingCard({ COACHING }: Props) {

    function ScoreRing({ score, delta }: { score: number; delta: number }) {
      const color = score >= 85 ? "#10b981" : score >= 70 ? "#f59e0b" : "#f43f5e";
      const r = 28, circ = 2 * Math.PI * r;
      return (
        <div className="relative w-16 h-16 flex-shrink-0">
          <svg width="64" height="64" style={{ transform: "rotate(-90deg)" }}>
            <circle cx="32" cy="32" r={r} fill="none" stroke="rgba(255,255,255,0.06)" strokeWidth="4" />
            <circle cx="32" cy="32" r={r} fill="none" stroke={color} strokeWidth="4"
              strokeDasharray={`${(score/100)*circ} ${circ}`} strokeLinecap="round"
              style={{ filter: `drop-shadow(0 0 5px ${color}80)` }} />
          </svg>
          <div className="absolute inset-0 flex flex-col items-center justify-center">
            <span className="text-sm font-bold text-white leading-none">{score}</span>
            <span className={`text-xs font-mono leading-none mt-0.5 ${delta >= 0 ? "text-emerald-400" : "text-rose-400"}`}>
              {delta >= 0 ? "+" : ""}{delta}
            </span>
          </div>
        </div>
      );
    }

    return (
        <div className="space-y-4">
          <div className="flex items-center gap-2 px-4 py-3 rounded-xl bg-cyan-500/5 border border-cyan-500/15">
            <Lightbulb size={14} className="text-cyan-400 flex-shrink-0" />
            <p className="text-sm text-slate-300">AI coaching tips are generated by analyzing speech patterns, empathy language, resolution rates, and QA scores across each agent's recent calls.</p>
          </div>
          <div className="grid gap-4">
            {COACHING.map(agent => (
              <div key={agent.agentId} className="bg-slate-900/60 border border-slate-700/30 rounded-xl p-5 backdrop-blur-sm">
                <div className="flex items-start gap-4">
                  <div className="flex flex-col items-center gap-2 flex-shrink-0">
                    <div className="w-12 h-12 rounded-full bg-gradient-to-br from-cyan-500 to-blue-600 flex items-center justify-center text-white text-sm font-bold">{agent.avatar}</div>
                    <ScoreRing score={agent.score} delta={agent.scoreDelta} />
                  </div>
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-3 mb-3">
                      <h3 className="font-semibold text-white">{agent.agent}</h3>
                      <span className="text-xs font-mono text-slate-500">{agent.callsReviewed} calls reviewed</span>
                      {agent.scoreDelta < 0 && (
                        <span className="text-xs px-2 py-0.5 rounded-full bg-rose-500/10 border border-rose-500/20 text-rose-400 font-mono flex items-center gap-1"><AlertTriangle size={10}/> Needs attention</span>
                      )}
                      {agent.scoreDelta > 5 && (
                        <span className="text-xs px-2 py-0.5 rounded-full bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 font-mono flex items-center gap-1"><Flame size={10}/> Top performer</span>
                      )}
                    </div>
                    <div className="grid md:grid-cols-2 gap-4">
                      <div>
                        <div className="text-xs font-mono text-emerald-400 mb-2 flex items-center gap-1.5"><Shield size={11}/> Strengths</div>
                        <ul className="space-y-1">{agent.strengths.map(s => <li key={s} className="flex items-start gap-2 text-sm text-slate-300"><span className="text-emerald-500 mt-0.5 text-xs">✓</span>{s}</li>)}</ul>
                      </div>
                      <div>
                        <div className="text-xs font-mono text-amber-400 mb-2 flex items-center gap-1.5"><Target size={11}/> Focus Areas</div>
                        <ul className="space-y-1">{agent.improvements.map(s => <li key={s} className="flex items-start gap-2 text-sm text-slate-300"><span className="text-amber-500 mt-0.5 text-xs">→</span>{s}</li>)}</ul>
                      </div>
                    </div>
                    <div className="mt-3 px-3 py-2 rounded-lg bg-slate-800/50 border border-slate-700/30">
                      <span className="text-xs font-mono text-violet-400">AI Note: </span>
                      <span className="text-xs text-slate-400">{agent.topIssue}</span>
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
    );
}